sudo: required #required to use docker
language: java
jdk: openjdk8

cache:
  directories:
    - .autoconf
    - $HOME/.m2

services:
  - docker

install:
  - cp .travis.settings.xml $HOME/.m2/settings.xml && mvn clean install

script:
  - echo "no tests!" # put your normal testing scripts here
  - ls -l

deploy:
  provider: script
  script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy"
  skip_cleanup: true
  on:
    branch: master

notifications:
  slack: $SLACK_URL